name: continuous integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies with pipenv
        run: pipenv install --python python${{ matrix.python-version }}
      - name: Test with pytest
        run: pipenv run pytest .
      - name: Check style with black
        run: pipenv run black --check .
